// This is to deploy an application of react or any other frontend using Node or npm

### STAGE 1: Build ###
FROM node:14.15-alpine3.12 AS build
WORKDIR /usr/src/app
COPY package*.json ./
COPY . .
RUN npm install
RUN npm run build
### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY certificate.crt /etc/nginx/domain.crt
COPY private.key /etc/nginx/domain.key 
COPY --from=build /usr/src/app/build /usr/share/nginx/html

## NGINX-CONF ##

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        listen [::]:80;
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_tokens off;

        server_name  198.187.28.6;
        ssl_certificate    /etc/nginx/domain.crt;
        ssl_certificate_key    /etc/nginx/domain.key;
        # include /etc/nginx/options-ssl-nginx.conf;
        # ssl_dhparam /etc/nginx/ssl-dhparams.pem;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;


        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
